# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Prav"
license = "MIT"
licenselink = "https://github.com/pravin/hugo-theme-prav/blob/master/LICENSE"
description = "Refined two column theme that's easy on the eyes"
homepage = "https://github.com/pravin/hugo-theme-prav/"
tags = ["website", "responsive", "disqus", "blog", "two-column"]
features = ["posts", "comments"]
min_version = "0.41"

[author]
  name = "Pravin Paratey"
  homepage = "https://cto.me.uk"

