baseURL = "https://example.com/"
languageCode = "en-gb"
title = "Hugo Theme - Prav"
theme = "prav"

pygmentsCodeFences = "true"
pygmentsStyle = "perldoc"

# If you want to track using GA or use disqus for comments, uncomment the
# below and add the right value
#googleanalytics = ""
#disqusShortname = ""

# The settings below are used throughout the theme.
# Please change them!
[params]
  title = "Hugo Theme - Prav"
  tagline = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  author = "Pravin Paratey"

# If you do not want a social icon, just comment it out
# Please update the following
[social]
  email = "mailto:pravin@paratey.com"
  facebook = "https://www.facebook.com/pravin.paratey"
  twitter = "http://twitter.com/pravin"
  medium = "https://www.medium.com/@pravin"
  github = "https://github.com/pravin"
  linkedin = "http://uk.linkedin.com/in/pravinp"


# Set unsafe mode to allow markdownify to work with goldmark
# This is important. Please do not delete. It is used to re-render markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true